version: "3"

services:
  account-service:
    build:
      context: apps/account
      dockerfile: ./Dockerfile
    hostname: account
    restart: always
    networks:
      - dtupay-network
    depends_on:
      dtupay-service:
        condition: service_started

  dtupay-service:
    build:
      context: apps/dtupay
      dockerfile: ./Dockerfile
    hostname: dtupay
    restart: always
    ports:
      - "8080:8080"
    networks:
      - dtupay-network
    depends_on:
      rabbitmq-service:
        condition: service_started


  payment-service:
    build:
      context: apps/payment
      dockerfile: ./Dockerfile
    hostname: payment
    restart: always
    networks:
      - dtupay-network
    depends_on:
      account-service:
        condition: service_started

  token-service:
    build:
      context: apps/token
      dockerfile: ./Dockerfile
    hostname: token
    restart: always
    networks:
      - dtupay-network
    depends_on:
      account-service:
        condition: service_started

  rabbitmq-service:
    image: rabbitmq:3-alpine
    restart: on-failure
    hostname: rabbitmq
    networks:
      - dtupay-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  dtupay-network:
    driver: bridge
